
// -*- C++ -*-
// $Id: Version.h 89744 2010-04-02 08:54:30Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 7
#define ACE_BETA_VERSION 8
#define ACE_VERSION "5.7.8"
